parameters:
  - name: CONTAINER_NAME
  - name: AZURE_CONTAINER_REGISTRY
  - name: DATABASE_URL
    type: string
    default: 'postgresql://postgres:7HrX26sHIZz8yffytPc0@autonomize-database-1002.cwpqzu4drrfr.us-east-1.rds.amazonaws.com:5432/lunary'
  
jobs:
- job: BuildAndPush
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # - checkout: self
  #   submodules: true
  #   persistCredentials: true
  - task: Docker@2
    displayName: Build image
    inputs:
      command: build
      repository: '${{ parameters.CONTAINER_NAME }}'
      containerRegistry: '${{ parameters.AZURE_CONTAINER_REGISTRY }}'
      dockerfile: '**/Dockerfile'
      buildArgs: |
        DATABASE_URL=${{ parameters.DATABASE_URL }}
      tags: |
        $(Build.BuildNumber)
        $(Build.SourceBranchName)
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'))
  - script: docker images
  - task: Docker@2
    displayName: Push image
    inputs:
      command: push
      repository: '${{ parameters.CONTAINER_NAME }}'
      containerRegistry: '${{ parameters.AZURE_CONTAINER_REGISTRY }}'
      tags: |
        $(Build.BuildNumber)
        $(Build.SourceBranchName)
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'))
  - script: |
      git tag $(Build.BuildNumber)
      git push origin $(Build.BuildNumber)
    displayName: Git Tag
    condition: and(succeeded(), in(variables['Build.Reason'], 'Manual', 'IndividualCI', 'BatchedCI'))