---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lunary-frontend
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.frontend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lunary-backend
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}