{{- if and (eq .Release.Name "lunary-frontend") (.Values.frontend.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: lunary-frontend
  labels:
    app: lunary-frontend
    {{- include "lunary.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: lunary-frontend
    {{- include "lunary.selectorLabels" . | nindent 4 }}
{{- end }}
---

{{- if and (eq .Release.Name "lunary-backend") (.Values.backend.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: lunary-backend
  labels:
    app: lunary-backend
    {{- include "lunary.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: lunary-backend
    {{- include "lunary.selectorLabels" . | nindent 4 }}
{{- end }}
