# Default values for lunary.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global configurations
global:
  environment: production

service:
  port: 4000  # Default backend port

autoscaling:
  enabled: false

# Frontend specific configurations
frontend:
  enabled: true
  ingress: true
  replicaCount: 2
  image:
    repository: "sprintregistry.azurecr.io/lunary"
    tag: ""
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

# Backend specific configurations
backend:
  enabled: true
  replicaCount: 2
  image:
    repository: "sprintregistry.azurecr.io/lunary"
    tag: ""
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

# Common configurations
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  name: "genesis-platform-sa"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: lunary.sprint.autonomize.dev
      paths:
        - path: /api
          pathType: Prefix
          serviceName: backend
        - path: /
          pathType: Prefix
          serviceName: frontend
  tls: []